### PR TITLE
add custom rate action

### PR DESCRIPTION
**Pull request by dymx101**
hi Hugo,
i have added a custom rate action for customised store rating, just for the case guys published their apps to an app store other than the apple or google one.

### CODE REVIEW

**Comment by Skyost** [comment]
Hi and thanks for your proposal,
I think it's not a bad idea but it would be better to put it in the [`showRateDialog`](https://github.com/Skyost/rate_my_app/blob/master/lib/src/core.dart#L87) method, no ?

**Comment by dymx101** [comment]
`showRateDialog` only accept `String` as action button, so seems no to me unless i change some of the constructors...

**Comment by Skyost** [comment]
I think we're gonna implement it as @DenchikBY suggested in #25.

**Comment by Skyost** [comment]
Done in f5b3c987f8159e1b745b27c27b420b84d5b3d395.

**Pull request closed without merging**
